jobs:

- job: UbuntuCurses
  pool:
    vmImage: ubuntu-latest

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
  - script: |
      sudo apt install -yq --no-install-recommends gfortran
    displayName: 'Install Linux prereqs'
  - script: |
      python -m pip install meson
      curl -Ls https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip -o ninja-linux.zip
      sudo unzip ninja-linux.zip -d /usr/local/bin/
    displayName: 'install Meson'
  - script: meson setup build
    env:
      FC: gfortran
    displayName: 'Meson Configure and Generate'
  - script: meson test -C build
    displayName: 'Meson build and test'
  - publish: build/meson-logs/testlog.txt
    condition: succeededOrFailed()
    artifact: TestLog_Ubuntu_Meson

- job: MacOS
  pool:
    vmImage: macOS-latest

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
  - script: |
      brew install gcc ninja
      python -m pip install meson
    displayName: 'Install Prereqs'
  - script: meson setup build
    env:
      FC: gfortran
      CC: gcc
    displayName: 'Meson Configure and Generate'
  - script: meson test -C build
    displayName: 'Meson build and test'
  - publish: build/meson-logs/testlog.txt
    condition: succeededOrFailed()
    artifact: TestLog_Mac_Meson

- job: Windows
  pool:
    vmImage: windows-latest

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
  - script: |
      cinst -y ninja mingw
      python -m pip install meson
    displayName: 'Install Prereqs'
  - script: meson setup build
    env:
      FC: gfortran
    displayName: 'Meson Configure and Generate'
  - script: meson test -C build
    displayName: 'Meson build and test'
  - publish: build/meson-logs/testlog.txt
    condition: succeededOrFailed()
    artifact: TestLog_Windows_Meson
